const MIN_NUM_DEFINED_COMPONENT_MODELS = 3
const MIN_LISTINGS_TO_EVALUATE = 4
const DAY_LIMIT = 30
const LISTING_LIMIT = 30
const LOGGING = false

module.exports = { MIN_NUM_DEFINED_COMPONENT_MODELS, MIN_LISTINGS_TO_EVALUATE, DAY_LIMIT, LISTING_LIMIT, LOGGING }