const mongoose = require('../Mongoose.js');
const UserModel = require('./UserModel.js')
const Schema = mongoose.Schema

const BuildSchema = new mongoose.Schema({
    title: String,
    user: { type: Schema.Types.ObjectId, ref: 'User' },
    cpu: {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            cores: Number,
            base_clock: Number,
            multithreading: Boolean,
            boost_clock: Number,
            integrated_graphics: String,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
    'video-card': {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            chipset: String,
            vram: Number,
            base_clock: Number,
            boost_clock: Number,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
    motherboard: {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            socket: String,
            form_factor: String,
            ram_slots: Number,
            max_ram: Number,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
    memory: {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            module_type: String,
            speed: Number,
            number_of_modules: Number,
            module_size: Number,
            total_size: Number,
            first_word_latency: Number,
            cas_timing: Number,
            price_per_gb: Number,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
    'hard-drive': {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            capacity: Number,
            price_per_gb: Number,
            storage_type: String,
            form_factor: String,
            interface: String,
            platter_rpm: String,
            cache_amount: String,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
    'power-supply': {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            form_factor: String,
            efficiency_rating: String,
            wattage: Number,
            modular: String,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
    case: {
        type: Object,
        properties: {
            _id: String,
            type: String,
            model: String,
            brand: String,
            form_factor: String,
            color: String,
            external_bays: Number,
            internal_bays: Number,
            psu_wattage: Number,
            side_panel: String,
            pcpp_price: Number,
            thirty_day_average: Number,
            thirty_day_listing_count: Number,
            thirty_day_time: Number,
        },
    },
});

const BuildModel = mongoose.model('Builds', BuildSchema, 'builds')

module.exports = BuildModel