import { CASE_PROPERTIES, CPU_PROPERTIES, HARD_DRIVE_PROPERTIES, MEMORY_PROPERTIES, MOTHERBOARD_PROPERTIES, POWER_SUPPLY_PROPERTIES, VIDEOCARD_PROPERTIES } from "../../component_enums/ComponentPropertiesEnums";

export const ComponentSpecs = Object.freeze({
    TYPE: 'cpu',
    MODEL: 'model',
    BRAND: 'brand',
    CORES: 'cores',
    BASE_CLOCK: 'base_clock',
    BOOST_CLOCK: 'boost_clock',
    MULTI_THREADING: 'multithreading',
    INTEGRATED_GRAPHICS: 'integrated_graphics',
    CHIPSET: 'chipset',
    VRAM: 'vram',
    SOCKET: 'socket',
    FORM_FACTOR: 'form_factor',
    RAM_SLOTS: 'ram_slots',
    MAX_RAM: 'max_ram',
    MODULE_TYPE: 'module_type',
    SPEED: 'speed',
    NUMBER_OF_MODULES: 'number_of_modules',
    MODULE_SIZE: 'module_size',
    TOTAL_SIZE: 'total_size',
    FIRST_WORD_LATENCY: 'first_word_latency',
    CAS_TIMING: 'cas_timing',
    PRICE_PER_GB: 'price_per_gb',
    CAPACITY: 'capacity',
    STORAGE_TYPE: 'storage_type',
    INTERFACE: 'interface',
    PLATTER_RPM: 'platter_rpm',
    CACHE_AMOUNT: 'cache_amount',
    EFFICIENCY_RATING: 'efficiency_rating',
    WATTAGE: 'wattage',
    MODULAR: "modular",
    COLOR: 'color',
    INTERNAL_BAYS: 'internal_bays',
    EXTERNAL_BAYS: "external_bays",
    PSU_WATTAGE: 'psu_wattage',
    SIDE_PANEL: 'side_panel',
    THIRTY_DAY_AVERAGE: 'thirty_day_average',
    PCPP_PRICE: 'pcpp_price',
})

export const LABELS_DICT = {
    [CPU_PROPERTIES.TYPE]: "CPU",
    [VIDEOCARD_PROPERTIES.TYPE]: "VideoCard",
    [MOTHERBOARD_PROPERTIES.TYPE]: "Motherboard",
    [MEMORY_PROPERTIES.TYPE]: "Memory",
    [HARD_DRIVE_PROPERTIES.TYPE]: "Hard-Drive",
    [POWER_SUPPLY_PROPERTIES.TYPE]: "Power-Supply",
    [CASE_PROPERTIES.TYPE]: "Case",
    [ComponentSpecs.BRAND]: 'Brand',
    [ComponentSpecs.MODEL]: 'Model',
    [ComponentSpecs.CORES]: 'Cores',
    [ComponentSpecs.BASE_CLOCK]: 'Base Clock',
    [ComponentSpecs.BOOST_CLOCK]: 'Boost Clock',
    [ComponentSpecs.VRAM]: 'VRAM',
    [ComponentSpecs.SOCKET]: 'Socket',
    [ComponentSpecs.FORM_FACTOR]: 'Form Factor',
    [ComponentSpecs.RAM_SLOTS]: 'RAM Slots',
    [ComponentSpecs.MAX_RAM]: 'Max RAM',
    [ComponentSpecs.MODULE_TYPE]: 'Module Type',
    [ComponentSpecs.SPEED]: 'Speed',
    [ComponentSpecs.NUMBER_OF_MODULES]: 'Number of Modules',
    [ComponentSpecs.MODULE_SIZE]: 'Module Size',
    [ComponentSpecs.TOTAL_SIZE]: 'Total Size',
    [ComponentSpecs.FIRST_WORD_LATENCY]: 'First Word Latency',
    [ComponentSpecs.CAS_TIMING]: 'CAS Timing',
    [ComponentSpecs.PRICE_PER_GB]: 'Price per GB',
    [ComponentSpecs.EFFICIENCY_RATING]: 'Efficiency Rating',
    [ComponentSpecs.WATTAGE]: 'Wattage',
    [ComponentSpecs.MODULAR]: 'Modular',
    [ComponentSpecs.THIRTYDAYAVERAGE]: '30-Day Average',
    [ComponentSpecs.PCPP_PRICE]: 'PCPP Price',
};